### ISSUE TITLE
NAN occurs during training

### ISSUE THREAD

**Issue by USTCXSC** [mazurowski-lab/swssl-for-anomaly-detection#1]
I set the epochs to 20 according to the experiment in the paper, and on the 12th epoch, the NAN appeared
<img width="980" alt="微信图片_20240210143811" src="https://github.com/mazurowski-lab/swssl-for-anomaly-detection/assets/101544690/1f017827-8c05-4014-afaf-347e2f11f520">

**Comment by haoyudong-97** [comment]
<img width="1431" alt="Screenshot 2024-02-11 at 7 57 35 AM" src="https://github.com/mazurowski-lab/swssl-for-anomaly-detection/assets/17803684/aabfa2f0-80ad-418d-9d75-eb135b6c9c61">
I confirm the code is working on my side, so the issue might be caused by different package versions. I have pytorch==1.13.1
